### ISSUE TITLE
Theme does not load because of an error in the Main.qml file relating to Type Login:

### ISSUE THREAD

**Issue by KHZ-INTL** [Eayu/sddm-theme-clairvoyance#2]
Error shown at logging in GUI:
The current theme cannot be loaded due to the error below, please select another theme.
file://usr/share/sddm/theme/clairvoyance/Main.qml:16:3 Type Login unavailable
file://usr/share/sddm/theme/... the rest is not readable because it is cutoff by screen height limit.

Hope that helps with resolving this issue.

**Comment by eayus** [comment]
Sorry for such a late reply, this error occurs when you haven't got QT5 installed (on arch just install package "qt5". I'll add this info to the readme tho.

**Comment by KHZ-INTL** [comment]
Hi Eayu,
Thank you for your help. Installed qt5 and now its working as it should. Great theme.

**Comment by jgbyrne** [comment]
I just needed the arch packages `qt5-base` and `qt5-quickcontrols` to fix this.
