### ISSUE TITLE
Add screenshot to metadata.desktop

### ISSUE THREAD

**Issue by ghost** [Eayu/sddm-theme-clairvoyance#3]
If you add `Screenshot=clairvoyance_screenshot.png` to `metadata.desktop`, the screenshot will appear in the sddm login selector as the preview. 

Right now the preview pane just says "No preview available".

Not a major issue by any means, but I thought I'd put it out there. Beautiful theme.

**Comment by eayus** [comment]
Done - just something that slipped my mind after creating it. I copied one of the base themes, deleted that line temporarily while I was developing the theme but forgot to add it in after.
