### ISSUE TITLE
Autofocus on passwordfield

### ISSUE THREAD

**Issue by larsemil** [Eayu/sddm-theme-clairvoyance#4]
First of all - I love this theme. Its so nice and easy on the eye.

BUT, when i choose my user by pressing enter the password-box shows up - BUT it does not get focused. How do i get it to do that? Pressing tab once works, but i'd like to autofocus the passwordfield so that i can start type my password.

**Comment by eayus** [comment]
Okay, this is something that I won't commit into the main code as it is a matter of preference, but I will provide instructions in the README on how to change this if you prefer. This is the easiest way I see of doing it:

Edit "Login.qml" and add a function around line 21 with the following content:
```
function focusPassword() {
    passwordInput.focus = true;
}
```

The edit "ChooseUser.qml" and replace line 25 (the one where it says "loginFrame.focus =true" with:
```
loginFrame.focusPassword();
```

Hope this works for you.

**Comment by vKnmnn** [comment]
for completeness:
to change this behaviour for mouseclicking as well, do the second replacement also in UserDelegate.qml on line 46

**Comment by larsemil** [comment]
Was looking for that. :) Thanks!

**Comment by eayus** [comment]
I will add an option in the theme.conf to enable autofocus password when I get a chance.

**Comment by eayus** [comment]
Okay, I've added an option in theme.conf where you can just set autoFocusPassword=true, and it will automatically focused the password. I've also added a small delay so that the animations don't overlap.
