### ISSUE TITLE
High DPI Session names overlapping

### ISSUE THREAD

**Issue by vKnmnn** [Eayu/sddm-theme-clairvoyance#5]
Hi there!

You have made a very nice theme, thank you!

I notice that my users sessions are all garbled up in the menu, wheter I enable HiDPI or set it off in sddm.conf

sddm-greeter --test does it right , but scales way too much

What can i try to resolve this behaviour?

**Comment by eayus** [comment]
Hi, unofortunately the highest resolution screen I have is 1920x1080, so I can't test if these fixes work. My guess is the HiDPI mode is scaling up the fonts, and they wont fit in the harcoded sized invisible 'box' around them. I think your best bet is to increase the height and width of the box. To do this edit the 'width' and 'height' properties on lines 42 and 43 respectively in Main.qml. When I get a chance I will edit the theme to detect if it in HiDPI mode and automatically change properties like this.
Hope this fixes your problem.

**Comment by vKnmnn** [comment]
i increased the width to 285, left height at 50, and reduced font size to 10. now `i3 (with debug log)` fits in there as it should. 
Font size 12 would have needed at least 400 width and looked to big.

Thanks for the help!

**Comment by vKnmnn** [comment]
looking at the video again, not changing the boxes at all, but decreasing Font size to 6 fits the original better.
So i tried out halving all the font sizes, and now it looks like the original. this seems to be a font-scaling issue indeed.
I also noticed you use Fira Font but don't list it as a dep anywhere.

**Comment by eayus** [comment]
Hi, glad you managed to solve your problem. I am currently doing some code refactoring and I will add an option in theme.conf for HPDI which you can set to automatically set the font sizes to 6. Nice spot on the dependency, I'll add that to the README.

**Comment by eayus** [comment]
I've added the option in theme.conf, just set enableHDPI=true in theme.conf (after updating to the latest version). If you have any other scaling issues on HDPI don't be afraid to open an issue, as I can't test it myself.

**Comment by vKnmnn** [comment]
All seems fine now, HDPI on or off both delivers non-overlapping textfields
although i feel, that scaling isn't correct, because everything's too big.
It's ok though
![greeter](https://user-images.githubusercontent.com/16045883/32787277-71a972c8-c956-11e7-80c5-9a0b9d7e0319.png)

**Comment by eayus** [comment]
I'm assuming SDDM/Qt is just automatically scaling everything up by integer values, so it will either look too big or too small. Aside from scaling everything up manually, I don't think there is an easy fix.
